<?php echo $this->form()->openTag($form); ?>
<div id="loginbox">

	<!--  start login-inner -->
	<div id="login-inner">
		<?php echo $this->error; ?>
		<table cellspacing="0" cellpadding="0" border="0">
		<tbody><tr>
			<th></th>
			<td>
			<?php 
				echo $this->formInput($form->get('username')); 
				echo $this->formElementErrors($form->get('username'));
			?>
			</td>
		</tr>
		<tr>
			<th></th>
			<td><?php 
				echo $this->formInput($form->get('password')); 
				echo $this->formElementErrors($form->get('password'));
			?></td>
		</tr>
		<tr>
			<th></th>
			<td>	<?php 
					echo $this->formInput($form->get('submit')); 
					?>
				</td>
		</tr>
		</tbody></table>
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
<!-- 	<a class="forgot-pwd" href="">Forgot Password?</a> -->
 </div>
 <?php echo $this->form()->closeTag($form); ?>