<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Contact Locations Admin</title>

        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/screen.css');

        $this->headLink()->appendStylesheet('/jqGrid/css/ui.jqgrid.css')
        ->appendStylesheet('/css/jquery.ui.datepicker.css')
        ->appendStylesheet('/plugins/ui.multiselect.css') ;
        
        $this->headScript()->prependFile('/js/jquery/jquery-1.4.1.min.js', 'text/javascript')
        ->prependFile('/js/jquery/ui.core.js', 'text/javascript')
        ->appendFile('/js/jquery/ui.checkbox.js', 'text/javascript')
        ->appendFile('/js/jquery/jquery.bind.js', 'text/javascript');
        
		?>

<!--[if IE]>
<link rel="stylesheet" media="all" type="text/css" href="css/pro_dropline_ie.css" />
<![endif]-->

</head>
<body> 
<!-- Start: page-top-outer -->
<div id="page-top-outer">    

<!-- Start: page-top -->
<div id="page-top">

	<!-- start logo -->
	<div id="logo">
<!-- 	<a href=""><img src="images/shared/logo.png" width="156" height="40" alt="" /></a>
 -->	</div>
	<!-- end logo -->
</div>
<!-- End: page-top -->

</div>
<!-- End: page-top-outer -->
	
<div class="clear">&nbsp;</div>
 
<?php 
    if($this->loggedInUser)
    {	
?>
 
<?php echo $this->partial('layout/top_menu_admin',(array)$this->loggedInUser);?>

<?php 
    }
?>

<!-- start content-outer ........................................................................................................................START -->
<div id="content-outer">
<!-- start content -->
<div id="content">

<?php echo $this->content; ?>

</div>
<!--  end content -->
<div class="clear">&nbsp;</div>
</div>
<!--  end content-outer........................................................END -->

<div class="clear">&nbsp;</div>
    
<!-- start footer -->         
<div id="footer">
</div>
<!-- end footer -->
 
</body>
</html>