<?php if ($this->pageCount): ?>
    <div class="pagination-container">
        <ul id="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="previous-off">
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled previous-off">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li>
                        <a class="current" href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="next">
                    <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled next">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>