<?php echo $this->doctype(); ?>
<html lang="en">
<head>
	<meta charset="utf-8" />

	<?php 
	
        echo $this->headLink()->appendStylesheet('/css_front/style.css')
        ->appendStylesheet('/css_front/flexslider.css');
        
        echo $this->headScript()->prependFile('/js/jquery-1.7.2.min.js')
        ->appendFile('/js/jquery.flexslider-min.js')
        ->appendFile('/js/functions.js', 'text/javascript');

        
	?>
	<!--[if lt IE 9]>
		<script src="/js/modernizr.custom.js"></script>
	<![endif]-->
	
	
</head>
<body>
	<!-- wrapper -->
	<div  id="wrapper">
		<!-- header -->
		<header>	
			<div class="shell">
				<h1 id="logo"><a href="#">my Logo</a></h1>
				<div class="contact">
					<p class="ico phone-ico"><span></span>+132 456 789</p>
				</div>
			</div>	
		</header>
		<!-- end of header -->
		<!-- navigation -->
		<nav id="navigation">
			<div class="shell">
				<ul>
					<li class="active" style="border:none;"><a href="#"><span></span>Home</a></li>
					<li><a href="#"><span class="bottom-arr"></span>About Us</a></li>
					<li><a href="#"><span class="bottom-arr"></span>News</a></li>
					<li><a href="#"><span class="bottom-arr"></span>Add</a></li>
					<li><a href="#"><span class="bottom-arr"></span>Videos</a></li>
					<li><a href="#"><span class="bottom-arr"></span>Contact Us</a></li>                                                                                                                                                                
				</ul>
			</div>	
		</nav>
		<!-- end of navigation -->
		<!-- slider-holder -->
		<div class="slider-holder">
			<div class="shell">
				<span class="slider-shadow"></span>
				<div class="slider flexslider">
					<ul class="slides">
						<li>
							<img src="/css_front/images/banner.png" alt="" />
							<!--<div class="slide-cnt">
								<h2>Innovative Design Solutions Ranging</h2>
								<p>Lorem ipsum dolor sit amet, con-<br />sectetur adipiscing elit. Praesent non tortor quis tellus euismod sodalestis elit lorem, vehicula sit amet dictum nec, congue venenatis quam. Cras fermentum scelerisque ma .. <a href="#">Read More</a></p>
								<a href="#" class="slider-btn">Explore Project</a>
							</div>-->
						</li>
						<li>
							<img src="/css_front/images/banner.png" alt="" />
							<!--<div class="slide-cnt">
								<h2>Innovative Design Solutions Ranging</h2>
								<p>Lorem ipsum dolor sit amet, con-<br />sectetur adipiscing elit. Praesent non tortor quis tellus euismod sodalestis elit lorem, vehicula sit amet dictum nec, congue venenatis quam. Cras fermentum scelerisque ma .. <a href="#">Read More</a></p>
								<a href="#" class="slider-btn">Explore Project</a>
							</div>-->
						</li>
						<li>
							<img src="/css_front/images/banner.png" alt="" />
							<!--<div class="slide-cnt">
								<h2>Innovative Design Solutions Ranging</h2>
								<p>Lorem ipsum dolor sit amet, con-<br />sectetur adipiscing elit. Praesent non tortor quis tellus euismod sodalestis elit lorem, vehicula sit amet dictum nec, congue venenatis quam. Cras fermentum scelerisque ma .. <a href="#">Read More</a></p>
								<a href="#" class="slider-btn">Explore Project</a>
							</div>-->
						</li>
						<li>
							<img src="/css_front/images/banner.png" alt="" />
							<!--<div class="slide-cnt">
								<h2>Innovative Design Solutions Ranging</h2>
								<p>Lorem ipsum dolor sit amet, con-<br />sectetur adipiscing elit. Praesent non tortor quis tellus euismod sodalestis elit lorem, vehicula sit amet dictum nec, congue venenatis quam. Cras fermentum scelerisque ma .. <a href="#">Read More</a></p>
								<a href="#" class="slider-btn">Explore Project</a>
							</div>-->
						</li>
						<li>
							<img src="/css_front/images/banner.png" alt="" />
							<!--<div class="slide-cnt">
								<h2>Innovative Design Solutions Ranging</h2>
								<p>Lorem ipsum dolor sit amet, con-<br />sectetur adipiscing elit. Praesent non tortor quis tellus euismod sodalestis elit lorem, vehicula sit amet dictum nec, congue venenatis quam. Cras fermentum scelerisque ma .. <a href="#">Read More</a></p>
								<a href="#" class="slider-btn">Explore Project</a>
							</div>-->
						</li>
					</ul>
				</div>
			</div>	
		</div>	
		<!-- end of slider-holder -->
		<!-- services -->
		
		<!-- end of services -->
		<!-- main -->
		<div class="main">
			<div class="shell">
				<section>
					<!-- content -->
					<div class="content1">
						<h2>Welcome To MY LOGO</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent non tortor quis tellus euismod sodales. Donec tincidunt auctor convallis. Nunc tincidunt nibh nec odio venenatis et condimentum nisl dapibus. Integer ipsum elit, commodo ac congue quis, varius at eros. Praesent tempus vulputate tortor eu feugiat. Maecenas bibendum suscipit molestie. Phasellus erat arcu, fringilla ac suscipit nec, lobortis at mi.</p>

						<p>Etiam interdum mauris quis nunc faucibus porttitor. Quisque tempor posuere pharetra. Sed fringilla placerat nulla. Etiam tincidunt ante eget arcu sodales scelerisque. Ut elit lorem, vehicula sit amet dictum nec, congue venenatis quam. Cras fermentum scelerisque ma</p>
                        <div class="tabs">
                        	<ul id="tabs">
                            <li style="margin:0px;"><a  class="tab_b " href="#" title="tab1">Top 50 Searches</a></li>
                            <li><a  class="tab_a" href="#" title="tab2">Top 50 Most Viewed  </a></li>
                            <li><a class="tab_c" href="#" title="tab3">Latest Additions </a></li>
                            <!--<li><a href="#" title="tab4">Four</a></li> -->   
                        </ul>
                        </div>
                            <div id="content" style="top:10px;"> 
        <div id="tab1">
            <h2>Lorem ipsum sit amet</h2>
            <p>Praesent risus nisi, iaculis nec condimentum vel, rhoncus vel dolor. Aenean nisi lectus, varius nec tempus id, dapibus non quam.</p>
            <p>Suspendisse ac libero mauris. Cras lacinia porttitor urna, vitae molestie libero posuere et. Mauris turpis tortor, mollis non vulputate sit amet, rhoncus vitae purus.</p>
    
            <h3>Pellentesque habitant</h3>
            <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.</p>    
        </div>
        <div id="tab2">
            <h2>Vivamus fringilla suscipit justo</h2>
            <p>Aenean dui nulla, egestas sit amet auctor vitae, facilisis id odio. Donec dictum gravida feugiat.</p>
            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras pretium elit et erat condimentum et volutpat lorem vehicula</p>
    
            <p>Morbi tincidunt pharetra orci commodo molestie. Praesent ut leo nec dolor tempor eleifend.</p>    
        </div>
        <div id="tab3">
            <h2>Phasellus non nibh</h2>
            <p>Non erat laoreet ullamcorper. Pellentesque magna metus, feugiat eu elementum sit amet, cursus sed diam. Curabitur posuere porttitor lorem, eu malesuada tortor faucibus sed.</p>
            <h3>Duis pulvinar nibh vel urna</h3>
            <p>Donec purus leo, porttitor eu molestie quis, porttitor sit amet ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec accumsan ornare elit id imperdiet. </p>
    
            <p>Suspendisse ac libero mauris. Cras lacinia porttitor urna, vitae molestie libero posuere et. </p>
        </div>
        <div id="tab4">
            <h2>Cum sociis natoque penatibus</h2>
            <p>Magnis dis parturient montes, nascetur ridiculus mus. Nullam ac massa quis nisi porta mollis venenatis sit amet urna. Ut in mauris velit, sed bibendum turpis.</p>
            <p>Nam ornare vulputate risus, id volutpat elit porttitor non. In consequat nisi vel lectus dapibus sodales. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent bibendum sagittis libero.</p>
    
            <h3>Imperdiet sem interdum nec</h3>
    
            <p>Mauris rhoncus tincidunt libero quis fringilla.</p>    
        </div>
    </div>
                            <script>
                            $(document).ready(function() {
                                $("#content div").hide(); // Initially hide all content
                                $("#tabs li:first").attr("id","current"); // Activate first tab
                                $("#content div:first").fadeIn(); // Show first tab content
                                
                                $('#tabs a').click(function(e) {
                                    e.preventDefault();        
                                    $("#content div").hide(); //Hide all content
                                    $("#tabs li").attr("id",""); //Reset id's
                                    $(this).parent().attr("id","current"); // Activate this
                                    $('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
                                });
                            })();
                            </script>
                        </div>
                        

<!-- aside -->
					<aside>
						<div class="widget">
							<h2>Category</h2>
							<ul>
                            	<li><a href="#">Automotive</a></li>
                                <li><a href="#">Financial Services</a></li>
                                <li><a href="#">Government</a></li>
                                <li><a href="#">Health and Medicine</a></li>
                                <li><a href="#">Internet</a></li>
                                <li><a href="#">Media</a></li>
                                <li><a href="#">Phone Companies</a></li>
                                <li><a href="#">Shipping</a></li>
                                <li><a href="#">Shopping</a></li>
                                <li><a href="#">Travel</a></li>
                                <li><a href="#">Utilities</a></li>
                            </ul>
							<div class="cl">&nbsp;</div>
						</div>
						<div class="widget1">
							<h2>Follow us on</h2>
							<div class="img-holder">
								<a href="#"><img src="/css_front/images/facebook.png" alt="" /></a>
							</div>
							<div class="img-holder">
								<a href="#"><img src="/css_front/images/twitter.png" alt="" /></a>
							</div>
							<div class="img-holder">
								<a href="#"><img src="/css_front/images/you.png" alt="" /></a>
							</div>
                            <div class="img-holder">
								<a href="#"><img src="/css_front/images/rss.png" alt="" /></a>
							</div>
							<div class="cl">&nbsp;</div>
						</div>
					</aside>
					<!-- end of aside -->
					<div class="cl">&nbsp;</div>

					</div>
					<!-- end of content -->
					
                    <div style="margin:10px auto auto auto; width:1000px;"><img src="/css_front/images/add_banner.png" width="1007" height="124"></div>
				</section>
			</div>
		</div>
		<!-- end of main -->
		<div id="footer-push"></div>
	</div>
	<!-- end of wrapper -->
	<div id="footer">
		<div class="shell">
			<nav class="footer-nav">
				<a href="#" class="active">Home</a>
				<a href="#">About Us</a>        
				<a href="#">news</a>
				<a href="#">Add Videos</a>
				<a href="#">Contact Us</a>
			</nav>
            <div style="text-align:center;">Copyright ©  2013, MYLOGO.com. All rights reserved. </div>
			<div style="text-align:center; margin:-43px 0 0 0;"><p class="copy">Design by <a href="http://cubeflick.com/" target="_blank">www.cubeflick.com/</a></p><div>
			<div class="cl">&nbsp;</div>
		</div>
	</div>
</body>
</html>