<?php echo $this->doctype(); ?>
<html lang="en">
<head>
	<meta charset="utf-8" />

	<?php 
	
        echo $this->headLink()->appendStylesheet('/css_front/style.css')
        	->appendStylesheet('/css_front/flexslider.css')
        	->appendStylesheet('/jqueryui/themes/ui-lightness/jquery-ui-1.10.3.custom.min.css');
        
        echo $this->headScript()->prependFile('/js/jquery-1.7.2.min.js')
        ->appendFile('/jqueryui/jquery-ui-1.10.3.custom.min.js')
        ->appendFile('/js/jquery.flexslider-min.js')
        ->appendFile('/js/functions.js', 'text/javascript');

        
	?>
	<!--[if lt IE 9]>
		<script src="/js/modernizr.custom.js"></script>
	<![endif]-->
	
	
</head>
<body>
	<!-- wrapper -->
	<div  id="wrapper">
		<!-- header -->
		<header>	
			<div class="shell">
				<h1 id="logo"><a href="#">my Logo</a></h1>
				<div class="contact">
					<p class="ico phone-ico"><span></span>+132 456 789</p>
				</div>
			</div>	
		</header>
		<!-- end of header -->
		<!-- navigation -->
		<nav id="navigation">
			<div class="shell">
				<?php 
				
				//echo "<pre>";
				//print_r($this->navigation('Navigation'));
				echo $this->navigation('navigation')->menu(); ?>
			</div>	
		</nav>

		<!-- end of navigation -->
		<!-- slider-holder -->
		<div class="slider-holder" >
			<div class="shell" >
				<span class="slider-shadow"></span>
				<div class="slider flexslider">
					<div style="padding:20px">
						<div>Enter Company Name:</div>
						<div><input type="text" name="company" id="company" /></div>
					</div>			
				</div>
			</div>	
		</div>	
		<!-- end of slider-holder -->
		<!-- services -->
		
		<!-- end of services -->
		<!-- main -->
		<div class="main">
			<div class="shell">
				<section>
					<!-- content -->
					<div class="content1">
					<div class="breadcrumb">
					<?php 
						echo $this->navigation('navigation')
						->breadcrumbs()->
						setMinDepth(0)
						->setLinkLast(false)
						->setSeparator(' : ');
					?>
					</div>
					
					
					<?php echo $this->layout()->content ?>
						
                        </div>
                        

<!-- aside -->
					<aside>
					
					<div>
						<div class="widget">
							<h1>Category</h1>
							<?php 
								echo ($this->listCategories());
							?>
								
								<div class="cl">&nbsp;</div>
						</div>
					</div>
						<div class="widget1">
							<h2>Follow us on</h2>
							<div class="img-holder">
								<a href="#"><img src="/css_front/images/facebook.png" alt="" /></a>
							</div>
							<div class="img-holder">
								<a href="#"><img src="/css_front/images/twitter.png" alt="" /></a>
							</div>
							<div class="img-holder">
								<a href="#"><img src="/css_front/images/you.png" alt="" /></a>
							</div>
                            <div class="img-holder">
								<a href="#"><img src="/css_front/images/rss.png" alt="" /></a>
							</div>
							<div class="cl">&nbsp;</div>
						</div>
					</aside>
					<!-- end of aside -->
					<div class="cl">&nbsp;</div>

					</div>
					<!-- end of content -->
					
                    <div style="margin:10px auto auto auto; width:1000px;"><img src="/css_front/images/add_banner.png" width="1007" height="124"></div>
				</section>
			</div>
		</div>
		<!-- end of main -->
		<div id="footer-push"></div>
	</div>
	<!-- end of wrapper -->
	<div id="footer">
		<div class="shell">
			<nav class="footer-nav">
				<a href="#" class="active">Home</a>
				<a href="#">About Us</a>        
				<a href="#">news</a>
				<a href="#">Add Videos</a>
				<a href="#">Contact Us</a>
			</nav>
            <div style="text-align:center;">Copyright ©  2013, MYLOGO.com. All rights reserved. </div>
			<div style="text-align:center; margin:-43px 0 0 0;"><p class="copy">Design by <a href="http://cubeflick.com/" target="_blank">www.cubeflick.com/</a></p><div>
			<div class="cl">&nbsp;</div>
		</div>
	</div>
</body>
</html>