<div>

<div class="widget">
							<h1>Category</h1>
							<ul>
							<?php 
							
							foreach ($category as $key => $cat)
							{
							
							?>
                            	<li><a href="<?php echo $this->url('subcategory', array('action' => 'subcategory')); ?>/<?php echo $cat->getName();?>"><?php echo $cat->getName();?></a></li>
                                
                                <?php 
							}
                                ?>
                            </ul>
							<div class="cl">&nbsp;</div>
						</div>
						
</div>