<div>

<div class="widget">
							<h1><?php echo $subcategory;?></h1>
							<ul>
							<?php 
							
							foreach($records as $cat)
    	{
    	 
							
							?>
                            	<li><a href="<?php echo $this->url('companylist', array('action' => 'companylist')); ?>/<?php echo $category;?>/<?php echo $subcategory;?>/<?php echo $cat['_listingName'];?>"><?php echo $cat['_listingName'];?></a></li>
                                
                                <?php 
							}
                                ?>
                            </ul>
							<div class="cl">&nbsp;</div>
						</div>
						
</div>