<div>
<TABLE CELLSPACING="0" CELLPADDING="0" STYLE="width:100%;" ID="listingResultsTable">


				<?php 
				foreach ($result as $key=>$value)
				{
				
				?>
     
                    <TR>
                        <TD CLASS="department">
                        <H2 STYLE="text-transform:capitalize;"><?php echo $value->getDepartment();?></H2>
                        <DIV STYLE="text-align:left;">
                  
                        </DIV>
                        
                        </TD>

                        <TD CLASS="details">

                        <DIV CLASS="label">Phone:</DIV>
                        <DIV CLASS="emphasisResult"><?php echo $value->getPhoneNumber();?></DIV>

                        <P>
                        <DIV CLASS="label">How to reach a live person:</DIV>
                        <DIV CLASS="normalResult"><?php echo $value->getStepToReach();?></DIV>

                        <P>
                        <DIV CLASS="label">Hours of Operation:</DIV>
                        <DIV CLASS="normalResult"><?php echo $value->getOperationHours();?></DIV>

                        <P>
                        <DIV CLASS="label">Email:</DIV>
                                                <DIV CLASS="normalResult"><?php echo $value-> getUserEmail();?></DIV>
                                                                        
                        <P>
                        <DIV CLASS="label">Customer service link:</DIV>
                                                <DIV ><A HREF="<?php echo $value->getCustomerServiceLink();?>" target="_blank">Click Here</A></DIV>
                                                
                        <P>
                        <DIV CLASS="label">Description:</DIV>
                        <DIV CLASS="normalResult"><?php echo $value->getDescription();?></DIV>

                        <!--
                        <P>
                        <DIV STYLE="text-align:center;margin:7px 0 7px 0;"><script type="text/javascript" src="http://cdn.socialtwist.com/2009032513495/script.js"></script><a class="st-taf" href="http://tellafriend.socialtwist.com:80" onclick="return false;" style="border:0;padding:0;margin:0;"><img alt="SocialTwist Tell-a-Friend" style="border:0;padding:0;margin:0;" src="http://images.socialtwist.com/2009032513495/button.png"onmouseout="hideHoverMap(this)" onmouseover="showHoverMap(this, '2009032513495', window.location, document.title)" onclick="cw(this, {id:'2009032513495', link: window.location, title: document.title });"/></a></DIV>
                        -->

                                                
                        </TD>
                    </TR>
                    <?php 
				}
                    ?>
                </TABLE>
</div>